name: Run PMD

on:
  workflow_call:

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Checkout Spark Template
        with:
          token: ${{ secrets.GH_PAT }}
          path: spark-template
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

